name: publish

on:
  push:
    tags:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    name: publish

    steps:
      - name: Publish
        env:
          TOKEN: ${{ secrets.GITLAB_SATIS_TRIGGER_TOKEN }}
        run: curl --request POST --form "token=$TOKEN" --form ref=master https://gitlab.com/api/v4/projects/16293012/trigger/pipeline